---
name: Aqua Tracee Security
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  tracee:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Start Tracee
        uses: aquasecurity/tracee-action@v0.4.0-stop

      - name: Run your tests
        run: echo "Run your tests here"

      - name: Stop Tracee
        uses: aquasecurity/tracee-action@v0.4.0-stop
        with:
          create_pr: true
          fail_on_diff: true
